### ISSUE TITLE
NameError in Windows CMD Line

### ISSUE THREAD

**Issue by kuthalam** [smkanvinde/UTECEClasses#4]
When I run "python FrontEnd.py" from the Windows cmd, the first input always returns:

Traceback (most recent call last):
  File "FrontEnd.py", line 18, in <module>
    givenCourse = input(">")
  File "<string>", line 1, in <module>
NameError: name 'EE364' is not defined

Works fine if I run from PyCharm though. Opening as an issue so if someone else can figure this out, that would be awesome. Relevant code is in "pythonDev" branch.

**Comment by kuthalam** [comment]
Never mind, the issue was I was not running it with Python3, which is necessary to make sure this works properly.
